// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_2Hs9VPyfFUOh2f8jVDZgBUd8SLwTNbg',
    appId: '1:111778015542:web:68c184770f07d97a20eb97',
    messagingSenderId: '111778015542',
    projectId: 'devmobile-5e5c2',
    authDomain: 'devmobile-5e5c2.firebaseapp.com',
    storageBucket: 'devmobile-5e5c2.appspot.com',
    measurementId: 'G-MQ7FRTC079',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBKo_4ip-1t49yRXEygVa261_yL3nYD6Y',
    appId: '1:111778015542:android:040af304f33c6b4e20eb97',
    messagingSenderId: '111778015542',
    projectId: 'devmobile-5e5c2',
    storageBucket: 'devmobile-5e5c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2ZhJVtEJTHTK_0Q-MAXxJlqQG-3tTnYQ',
    appId: '1:111778015542:ios:0cf4c5c46987e0df20eb97',
    messagingSenderId: '111778015542',
    projectId: 'devmobile-5e5c2',
    storageBucket: 'devmobile-5e5c2.appspot.com',
    iosBundleId: 'com.example.m2DevmobileMunoz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2ZhJVtEJTHTK_0Q-MAXxJlqQG-3tTnYQ',
    appId: '1:111778015542:ios:fed9a81f455e800120eb97',
    messagingSenderId: '111778015542',
    projectId: 'devmobile-5e5c2',
    storageBucket: 'devmobile-5e5c2.appspot.com',
    iosBundleId: 'com.example.m2DevmobileMunoz.RunnerTests',
  );
}
